<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>MySpawnerController.Swagger</RootNamespace>
    <AssemblyName>MySpawnerController.Swagger</AssemblyName>
    <LangVersion>12</LangVersion>
  </PropertyGroup>
</Project>
