<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>GridSpawner.Api</RootNamespace>
    <AssemblyName>GridSpawner.Api</AssemblyName>
    <LangVersion>12</LangVersion>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GridSpawner.Shared\GridSpawner.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.4" />
  </ItemGroup>

  <!-- Game DLLs -->
  <ItemGroup>
    <Reference Include="VRage">
      <HintPath>D:\SteamLibrary\steamapps\common\SpaceEngineers\Bin64\VRage.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VRage.Game">
      <HintPath>D:\SteamLibrary\steamapps\common\SpaceEngineers\Bin64\VRage.Game.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VRage.Math">
      <HintPath>D:\SteamLibrary\steamapps\common\SpaceEngineers\Bin64\VRage.Math.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Sandbox.Common">
      <HintPath>D:\SteamLibrary\steamapps\common\SpaceEngineers\Bin64\Sandbox.Common.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Sandbox.Game">
      <HintPath>D:\SteamLibrary\steamapps\common\SpaceEngineers\Bin64\Sandbox.Game.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>
